### ISSUE TITLE
Watcher for file changes

### ISSUE THREAD

**Issue by DatKyle** [OldhamMade/phoenix_sass#46]
Hi,

Does this have a watcher to watch for changes or does it recompile the sass/scss files all reload?

**Comment by OldhamMade** [comment]
Hi, yes, adding phoenix_sass to your project using the steps in the README will ensure that your files are watched and app is reloaded when any sass file changes.

However, this project is no longer maintained. https://github.com/CargoSense/dart_sass covers all the same benefits with a more modern Sass compiler, and is the library I now use instead of phoenix_sass. I would recommend using that project instead.
