### ISSUE TITLE
Protocol.Undefined error when running mix task

### ISSUE THREAD

**Issue by valeth** [OldhamMade/phoenix_sass#7]
Whenever I'm trying to run `mix phx.sass` I'm getting the following error:

```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:error, :bad_name} of type Tuple
    (elixir 1.11.0) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.11.0) lib/string/chars.ex:22: String.Chars.to_string/1
    (phoenix_sass 0.1.6) lib/mix/tasks/compile.phoenix_sass.ex:21: Mix.Tasks.Compile.PhoenixSass.run/1
    (mix 1.11.0) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.11.0) lib/code.ex:931: Code.require_file/2
```

This only happens when running the task, live reloading is working fine.

The configuration is pretty much the same as in the readme, and there is one single scss source file in the `priv/sass` directory.
Relatively new to Elixir, so I don't know if there's a way to get a more detailed stack trace.

**Comment by OldhamMade** [comment]
@valeth this happens when the `:code.priv_dir/1` call returns `nil`. I'll improve the error message here, but in general it's not something I can fix from the library's side. You may want to compare your config files with the README to make sure you don't have `priv/` at the beginning of your pattern, as that has been removed in the latest release.
